### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by dirkseidensticker** [ISAAKiel/postAAR-python#17]
Zip'ing the github repo and trying to manually load the plugin results in the following error message:

```
Konnte Erweiterung 'postAAR-python-master' nicht laden aufgrund eines Fehlers beim Aufruf der classFactory() Methode 

ModuleNotFoundError: No module named 'postAAR' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/dirks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\postAAR-python-master\__init__.py", line 29, in classFactory
    from .src.script.gui.postaar import postAAR
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/dirks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\postAAR-python-master\src\script\gui\postaar.py", line 36, in 
    from .postaar_task import postAARTask
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/dirks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\postAAR-python-master\src\script\gui\postaar_task.py", line 4, in 
    from postAAR.src.script.algorithm import helper as hlp
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'postAAR'


Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.22.1-Białowieża Białowieża, 663dcf8fb9 

Python-Pfad:
C:/OSGeo4W/apps/qgis/./python
C:/Users/dirks/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/dirks/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\GDAL-3.4.0-py3.9-win-amd64.egg
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/dirks/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

Windows 11 Pro (22H2)

**Comment by dirkseidensticker** [comment]
Rename ZIP to postAAR and try again!
