### ISSUE TITLE
Python-path error on Mac?

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/postAAR-python#2]
On Mac (OS 10.13.6, QGIS 3.6), the QGIS-python-postAAR loads and the GUI is configurable as expected but on execution the following error is thrown which seems related to the path:

`File "/Users/nils/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-qgis_multicore/postaar.py", line 263, in run
              subprocess.call([os.path.join(os.__file__.split("lib")[0],"python"), os.path.dirname(os.path.abspath(__file__)) + '\\postaar_algorithm.py', str(ntpath.basename(transferfile.name)), '-o', str(ntpath.basename(outputfile.name)), '-smax', str(maximum_length_of_side), '-smin', str(minimum_length_of_side), '-sdiff',str(max_diff_side), '-dmax', str(maximum_length_of_diagonal), '-dmin', str(minimum_length_of_diagonal), '-ddiff',str(max_diff_diagonal), '-cores', str(number_of_computercores)])
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 287, in call
              with Popen(*popenargs, **kwargs) as p:
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 729, in __init__
              restore_signals, start_new_session)
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1364, in _execute_child
              raise child_exception_type(errno_num, err_msg, err_filename)
             OSError: [Errno 8] Exec format error: '/Library/Frameworks/Python.framework/Versions/3.6/python'
             `

**Comment by WerthersEchte** [comment]
Please test the changes implemented on branch [https://github.com/ISAAKiel/postAAR-python/tree/linux_and_mac](url) in commit [https://github.com/ISAAKiel/postAAR-python/commit/99ad01f05620767fdae0fb1914631a33f92d0eb7](url)

**Comment by nmueller18** [comment]
Thanks for the quick fix! Unfortunately, this fix opens QGIS in a new instance and this has of course no access to the point file.

**Comment by WerthersEchte** [comment]
Ok. Next try!
Please test the changes implemented on brach [https://github.com/ISAAKiel/postAAR-python/tree/linux_and_mac](url) in commit [https://github.com/ISAAKiel/postAAR-python/commit/3e14e22b7e98ff410753bf8bdbb6907c3d1299a4](url)

**Comment by nmueller18** [comment]
WE are getting closer!

Here is the latest error message:

`2019-10-16T15:08:04     WARNING    Traceback (most recent call last):
              File "/Users/nils/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-linux_and_mac/postaar.py", line 271, in run
              subprocess.check_call(executable + [ os.path.join(os.path.dirname(os.path.abspath(__file__)), 'postaar_algorithm.py'), str(ntpath.basename(transferfile.name)), '-o', str(ntpath.basename(outputfile.name)), '-smax', str(maximum_length_of_side), '-smin', str(minimum_length_of_side), '-sdiff',str(max_diff_side), '-dmax', str(maximum_length_of_diagonal), '-dmin', str(minimum_length_of_diagonal), '-ddiff',str(max_diff_diagonal), '-cores', str(number_of_computercores)])
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 306, in check_call
              retcode = call(*popenargs, **kwargs)
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 287, in call
              with Popen(*popenargs, **kwargs) as p:
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 729, in __init__
              restore_signals, start_new_session)
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1364, in _execute_child
              raise child_exception_type(errno_num, err_msg, err_filename)
             FileNotFoundError: [Errno 2] No such file or directory: 'python3': 'python3'`

**Comment by nmueller18** [comment]
Progress? With the patch `, shell=True` at least the error code is a different one:

> 2019-11-16T13:11:14     WARNING    Traceback (most recent call last):
              File "/Users/Nils/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-linux_and_mac/postaar.py", line 271, in run
              subprocess.check_call(executable + [ os.path.join(os.path.dirname(os.path.abspath(__file__)), 'postaar_algorithm.py'), str(ntpath.basename(transferfile.name)), '-o', str(ntpath.basename(outputfile.name)), '-smax', str(maximum_length_of_side), '-smin', str(minimum_length_of_side), '-sdiff',str(max_diff_side), '-dmax', str(maximum_length_of_diagonal), '-dmin', str(minimum_length_of_diagonal), '-ddiff',str(max_diff_diagonal), '-cores', str(number_of_computercores)], shell=True)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 347, in check_call
              raise CalledProcessError(retcode, cmd)
             subprocess.CalledProcessError: Command '['python3', '/Users/Nils/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-linux_and_mac/postaar_algorithm.py', 'postAAR0hsk7rnx', '-o', 'postAARm73pxjz7', '-smax', '20.0', '-smin', '10.0', '-sdiff', '0.06', '-dmax', '142.0', '-dmin', '100.0', '-ddiff', '1.0', '-cores', '4']' returned non-zero exit status 127.

Now, there is a "CalledProcessError" ...

**Comment by nmueller18** [comment]
It seems that postAAR still does not find 'python3', despite the fact that QGIS3.10 brings it own python3.7 with it.
In QGIS, the python-related settings are as follows, in case this helps:

PYTHONHOME: /Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current
PYTHONPATH: /Applications/QGIS3.10.app/Contents/Resources/python

**Comment by nmueller18** [comment]
Even more progress? The error vanishes completely if the path is hardcoded in line 264 in `postaar.py` as `/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/bin/python3`
This is less than ideal, of course, because the code only works with QGIS3.10.

Additionally, now the algorithm reads in the data and then obviously closes silently. At least, there is no further feedback, not to speak of any of the files supposed to be generated.

**Comment by nmueller18** [comment]
Unfortunatley, the error persists, in either combination of QGIS 3.4 (LTR) or 3.10 and postAAR-python-linux_and_mac or postAAR-python-minimum_bounding_rectangle:

QGIS 3.10

﻿2020-02-19T21:28:59     WARNING    Traceback (most recent call last):
              File "/Users/nilsmuller-scheeel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-linux_and_mac/postaar.py", line 271, in run
              subprocess.check_call(executable + [ os.path.join(os.path.dirname(os.path.abspath(__file__)), 'postaar_algorithm.py'), str(ntpath.basename(transferfile.name)), '-o', str(ntpath.basename(outputfile.name)), '-smax', str(maximum_length_of_side), '-smin', str(minimum_length_of_side), '-sdiff',str(max_diff_side), '-dmax', str(maximum_length_of_diagonal), '-dmin', str(minimum_length_of_diagonal), '-ddiff',str(max_diff_diagonal), '-cores', str(number_of_computercores)], shell=True)
              File "/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/subprocess.py", line 347, in check_call
              raise CalledProcessError(retcode, cmd)
             subprocess.CalledProcessError: Command '['python3', '/Users/nilsmuller-scheeel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-linux_and_mac/postaar_algorithm.py', 'postAAR1o1bpymp', '-o', 'postAARhyjyu9pk', '-smax', '20.0', '-smin', '1.0', '-sdiff', '0.05', '-dmax', '142.0', '-dmin', '100.0', '-ddiff', '1.0', '-cores', '4']' returned non-zero exit status 127.
             
2020-02-19T21:30:35     WARNING    Traceback (most recent call last):
              File "/Users/nilsmuller-scheeel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-minimum_bounding_rectangle/postaar.py", line 206, in run
              self.dlg = postAARDialog()
              File "/Users/nilsmuller-scheeel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-minimum_bounding_rectangle/postaar_dialog.py", line 57, in __init__
              executable = sys.executable
             NameError: name 'sys' is not defined
             

QGIS 3.4
             
             ﻿2020-02-19T21:35:07     WARNING    Traceback (most recent call last):
                           File "/Users/nilsmuller-scheeel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-minimum_bounding_rectangle/postaar.py", line 206, in run
                           self.dlg = postAARDialog()
                           File "/Users/nilsmuller-scheeel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-minimum_bounding_rectangle/postaar_dialog.py", line 57, in __init__
                           executable = sys.executable
                          NameError: name 'sys' is not defined

2020-02-19T21:37:45     WARNING    Traceback (most recent call last):
              File "/Users/nilsmuller-scheeel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-linux_and_mac/postaar.py", line 271, in run
              subprocess.check_call(executable + [ os.path.join(os.path.dirname(os.path.abspath(__file__)), 'postaar_algorithm.py'), str(ntpath.basename(transferfile.name)), '-o', str(ntpath.basename(outputfile.name)), '-smax', str(maximum_length_of_side), '-smin', str(minimum_length_of_side), '-sdiff',str(max_diff_side), '-dmax', str(maximum_length_of_diagonal), '-dmin', str(minimum_length_of_diagonal), '-ddiff',str(max_diff_diagonal), '-cores', str(number_of_computercores)], shell=True)
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 311, in check_call
              raise CalledProcessError(retcode, cmd)
             subprocess.CalledProcessError: Command '['python3', '/Users/nilsmuller-scheeel/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/postAAR-python-linux_and_mac/postaar_algorithm.py', 'postAARi62kkm26', '-o', 'postAARz09y40jt', '-smax', '20.0', '-smin', '1.0', '-sdiff', '0.05', '-dmax', '142.0', '-dmin', '100.0', '-ddiff', '1.0', '-cores', '4']' returned non-zero exit status 127.

**Comment by nmueller18** [comment]
This is solved in this [commit](https://github.com/ISAAKiel/postAAR-python/commit/122882c7ab72fce75354f2c3c79687eac9b9914a). When implemented, I think the issue could be closed.

**Comment by nmueller18** [comment]
Actually, this can be closed now, as it is replicated by a newer issue.
